service: lambda-relatorio

frameworkVersion: '3'

provider:
  name: aws
  runtime: java25
  region: us-east-2

  vpc:
    securityGroupIds:
      - Fn::ImportValue: lambda-feedback-LambdaSecurityGroupId
    subnetIds:
      - subnet-0ee0a1dd869db04c7
      - subnet-0da578789a8cb50e6

  environment:
    SNS_TOPIC_ARN: arn:aws:sns:us-east-2:990773979941:feedback-critico
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_MASTER_USERNAME}
    DB_PASSWORD: ${env:DB_MASTER_PASSWORD}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: arn:aws:sns:us-east-2:990773979941:feedback-critico

package:
  artifact: target/function.zip

functions:
  relatorio:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    timeout: 30
    events:
      - schedule:
          rate: cron(0 8 ? * MON *)
          enabled: true
          description: Dispara relatorio semanal toda segunda-feira as 08:00 UTC